[package]
name = "axuser"
version = "0.1.0"
edition = "2021"
authors = ["Jiayu Chen <c0percn@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axruntime = { path = "../axruntime", features = ["syscall", "fs"] }
